const locators = {
  "Button with text  Login": `//button[normalize-space()='Login']`,
  "Cell in Tbody": `tbody > tr:nth-of-type(1) > td:nth-of-type(1)`,
  "Div in Div": `((//header)[2]//div)[1]`,
  "Div with text  elements": `//div[normalize-space()='elements']`,
  "Div with text  Experiments  2nd": `(//div[normalize-space()='Experiments'])[2]`,
  "Div with text  GMT 05 30 Asia Kolkata": `//div[normalize-space()='GMT+05:30 Asia/Kolkata']`,
  "Div with text  Hello  Ayush Alphabin": `//div[normalize-space()='Hello, Ayush Alphabin']`,
  "Div with text  styles": `//div[normalize-space()='styles']`,
  "Header 2nd": `(//header/div)[2]`,
  "Input with placeholder  Enter  organization  name": `input[placeholder="Enter organization name"]`,
  "Input with placeholder  Enter your email  1st": `(//input[@placeholder='Enter your email'])[1]`,
  "Input with placeholder  Search": `input[placeholder="Search"]`,
  "Input with placeholder  Select  a  timezone": `input[placeholder="Select a timezone"]`,
  "Input with placeholder  Set  full  name": `input[placeholder="Set full name"]`,
  "Input with text  Target page": `//div[normalize-space()='Target page']//input`,
  "Listbox in Div": `div[role="listbox"] > div:nth-of-type(2)`,
  "Menu in Div": `div[role="menu"] > div > div:nth-of-type(1)`,
  "P": `//p[contains(text(), 'Organization updated successfu')]`,
  "P in Div": `div > section > p:nth-of-type(1)`,
  "P in Form": `form > div:nth-of-type(1) > p`,
  "P in Form_1": `form > div:nth-of-type(2) > p:nth-of-type(1)`,
  "P starts with text  Delete organization  3rd": `(//p[starts-with(normalize-space(), 'Delete organization')])[3]`,
  "P starts with text  Delete organization  4th": `(//p[starts-with(normalize-space(), 'Delete organization')])[4]`,
  "P with text  Client-side  2nd": `(//p[normalize-space()='Client-side'])[2]`,
  "P with text  Create": `//p[normalize-space()='Create']`,
  "P with text  Create an Experiment": `//p[normalize-space()='Create an Experiment']`,
  "P with text  Delete organization  2nd": `(//p[normalize-space()='Delete organization'])[2]`,
  "P with text  Demo Experiment": `//p[normalize-space()='Demo Experiment']`,
  "P with text  Login to your account": `//p[normalize-space()='Login to your account']`,
  "P with text  Logout": `//p[normalize-space()='Logout']`,
  "P with text  New organization": `//p[normalize-space()='New organization']`,
  "P with text  Variant created successfully": `//p[normalize-space()='Variant created successfully']`,
  "P with text  Web editor is closed": `//p[normalize-space()='Web editor is closed']`,
  "P_1": `//p[contains(text(), 'Organization deleted successfu')]`,
  "Password Input": `input[name="password"]`,
  "Span with text  A A": `//span[normalize-space()='A A']`,
  "Span with text  Back": `//span[normalize-space()='Back']`,
  "Span with text  Create an Experiment": `//span[normalize-space()='Create an Experiment']`,
  "Span with text  Create experiment": `//span[normalize-space()='Create experiment']`,
  "Span with text  Edit  1st": `(//span[normalize-space()='Edit'])[1]`,
  "Span with text  Variant 1": `//span[normalize-space()='Variant 1']`,
  "Span with text  Variants": `//span[normalize-space()='Variants']`,
  "Variant iFrame": '.body-content > iframe',
  "Navigation H1 inside iFrame": `nav > h1`,
  "Hero Content H2 inside iFrame": `.hero-content > h2`,
  "Span Variant B": `//span[normalize-space()='Variant B']`,
  "Div in Div 3rd": `.v-list.v-sheet.theme--light.v-list--dense.v-list--flat > div:nth-child(3)`,
  "Span Variant A": `//span[normalize-space()='Variant A']`,
  "Div H2 in iframe": 'div > h2',
  "Publish button": `//p[normalize-space()='Publish']`
};

module.exports = { locators };
